//! Canonical manifest of `tests/command/status_wave0_test.rs` test names
//! (plan-20260714 §B.9).
//!
//! This constant is the single source of truth for the wave-0 status test
//! set: `compat_status_wave0_register` asserts bidirectional set equality
//! against the `#[test]`/`#[tokio::test]` declarations parsed from the
//! module source (it must not recursively invoke Cargo — see the gate's
//! module docs) and strict alphabetical ordering. Add or remove a test in
//! the module and this list together — never edit only one side.
//!
//! Tests gated `#[cfg(unix)]` in the module must additionally be named in
//! [`STATUS_WAVE0_TESTS_UNIX_ONLY`], the canonical platform inventory
//! (asserted unique and a subset of the full list). Source-level parsing
//! is `cfg`-independent, so the gate compares the full set on every
//! platform. Both lists stay in this one file so the manifest remains the
//! single source of truth.

pub const STATUS_WAVE0_TESTS: &[&str] = &[
    "api_warning_concurrent_isolated",
    "api_warning_no_global_exit_pollution",
    "api_warning_survives_await",
    "bare_null_emits_porcelain_v1",
    "bare_z_emits_porcelain_v1",
    "blob_evidence_computed_pair_rejects_exact",
    "blob_evidence_unknown_rejects_exact",
    "cache_fallback_still_fails_closed_on_io_blocked",
    "cached_conflicts_with_rename_flags",
    "chain_rename_default_untracked_d_and_question",
    "chain_rename_two_records",
    "check_dirty_blocked_rows_never_mutate_the_cache",
    "check_dirty_ioblocked_does_not_mutate_cache",
    "check_dirty_ioblocked_emits_warning_and_exit_nine",
    "check_dirty_modified_row_content_hash_failure_is_blocked_and_kept",
    "cluster_stops_at_value_option",
    "comparison_budget_is_shared_across_both_detection_sides",
    "config_copy_fail_closed",
    "core_quote_path_invalid_fail_closed",
    "diff_and_status_agree_on_duplicate_content_pairings",
    "diff_and_status_agree_on_inexact_stages",
    "exit_code_ioblocked_is_one",
    "exit_warning_over_dirty_cache_fallback",
    "exit_warning_over_dirty_ioblocked_json",
    "find_renames_after_double_dash_is_a_pathspec",
    "find_renames_raw_grammar_and_last_wins",
    "generate_short_status_entries_api",
    "gitlink_missing_object_exact_by_oid_mode",
    "gitlink_never_pairs_with_a_regular_blob",
    "global_after_subcommand_is_not_scanned_as_a_cluster",
    "global_short_value_contains_z_not_format",
    "human_rename_long_format",
    "human_rename_quotes_control_characters",
    "ioblocked_scan_does_not_replace_dirty_cache",
    "json_base_and_rename_completeness_matrix",
    "json_exit_nine_always_has_a_structured_warning",
    "json_inexact_reordered_score_100",
    "json_inexact_spanhash_score_floor",
    "json_io_blocked_is_clean_false",
    "json_io_blocked_non_utf8_path_reversible",
    "json_io_blocked_rename_branch_schema",
    "json_io_blocked_schema_snapshot",
    "json_io_blocked_staged_field_survives_subdirectory",
    "json_nested_unstaged_renamed_survives",
    "json_rename_rm_partial_chain",
    "json_repo_relative_from_subdir",
    "json_scan_ioblocked_reports_partial_without_writing_cache",
    "json_scan_with_pathspec_reports_blocks_outside_it",
    "json_warnings_schema_snapshot",
    "main_scan_ioblocked_keeps_ignored_json",
    "main_scan_ioblocked_keeps_prior_sibling_json",
    "main_scan_mid_iteration_readdir_error_reports_partial",
    "malformed_index_oid_rejected_at_decode",
    "missing_head_object_fails_closed_not_panics",
    "no_head_staged_rename",
    "non_utf8_arguments_do_not_abort_the_process",
    "non_utf8_path_skips_rename_not_status",
    "normalize_ignores_diff_pathspec_status",
    "null_after_separator_ignored",
    "object_fault_warning_is_deduplicated_across_both_sides",
    "object_read_budget_exceeded_skips_inexact_only",
    "object_read_corrupt_blob_skips_inexact_only",
    "object_read_corrupt_warning_is_deduplicated",
    "object_read_missing_blob_skips_inexact_only",
    "object_read_missing_warning_is_deduplicated",
    "object_read_unavailable_blob_skips_inexact_only",
    "object_read_unavailable_warning_is_deduplicated",
    "pathspec_filter_keeps_non_event_worktree_warnings",
    "pathspec_old_only_new_only_matrix",
    "porcelain_quote_path_utf8_non_ascii",
    "porcelain_untracked_directory_marker_survives_projection",
    "porcelain_v1_rename_output_stays_add_delete",
    "porcelain_v1_uses_rename_arrow_when_detected",
    "porcelain_v2_non_rename_rows_from_subdirectory_keep_real_metadata",
    "porcelain_v2_rename_from_subdirectory_keeps_real_metadata",
    "porcelain_v2_rename_unreadable_mode_fails_closed",
    "porcelain_v2_staged_deletion_spells_absent_sides_as_zero",
    "porcelain_v2_staged_modify_then_worktree_rename_emits_mr",
    "porcelain_v2_staged_rename_mode_hash_fields",
    "porcelain_v2_unmerged_row_from_subdirectory_keeps_real_worktree_mode",
    "porcelain_v2_unmerged_u_line",
    "porcelain_v2_unstaged_dot_r_hash_fixup",
    "porcelain_v2_z_rename_raw_bytes_with_tab_paths",
    "porcelain_v2_z_rename_record_nul_paths",
    "porcelain_z_non_utf8_base_status_raw_bytes",
    "probe_budget_aggregates_across_sibling_roots",
    "probe_budget_bounds_wide_directory",
    "probe_complete_consumes_dir_marker",
    "probe_complete_entries_sorted",
    "probe_dest_rejects_casefold_alias",
    "probe_dest_rejects_ignored",
    "probe_dest_rejects_tracked_path",
    "probe_dest_rejects_unmerged",
    "probe_dir_eacces_fail_closed",
    "probe_direct_file_and_symlink_roots_are_candidates",
    "probe_directory_symlink_is_leaf",
    "probe_eacces_then_truncated_keeps_both",
    "probe_excludes_uninitialized_gitlink_dir",
    "probe_glob_pathspec_keeps_blocked_directory_relevant",
    "probe_ignored_subtree_pruned_before_enumeration",
    "probe_marker_collapse_is_per_root",
    "probe_marker_kept_when_directory_has_unconsumed_candidates",
    "probe_never_enters_libra_or_git_metadata",
    "probe_never_reads_a_non_regular_candidate",
    "probe_pathspec_outside_eacces_not_propagated",
    "probe_records_escape_for_a_metadata_root_behind_a_symlink",
    "probe_rejects_a_directly_selected_nested_repository_root",
    "probe_roots_dedup_nested_ancestors",
    "probe_roots_exclude_only_repo_root",
    "probe_roots_icase_falls_back_repo_root",
    "probe_skipped_when_renames_disabled",
    "probe_skipped_when_untracked_disabled",
    "probe_symlinked_escape_is_reported_not_followed",
    "probe_truncated_keeps_dir_marker",
    "quiet_does_not_bypass_io_blocked_fail_closed",
    "quiet_unreadable_untracked_dir_fails_closed",
    "quote_path_always_escapes_control_bytes",
    "quote_path_always_escapes_tab",
    "quote_path_escape_matrix_and_cascade",
    "racily_clean_entry_is_content_compared_not_trusted",
    "raw_base64_encodes_platform_native_units",
    "ref_with_mismatched_hash_kind_fails_closed",
    "rename_config_cli_find_renames_overrides_false",
    "rename_config_status_renames_false_disables",
    "rename_empty_file_exact_pair_only",
    "rename_exact_staged_detected_by_default",
    "rename_from_subdirectory_detected",
    "rename_inexact_content_change_detected",
    "rename_json_includes_score_and_side",
    "rename_limit_config_cascade",
    "rename_limit_three_scope_cascade_and_invalid_winner",
    "rename_limit_warning_exit_nine_over_dirty",
    "rename_no_renames_flag_splits_add_delete",
    "rename_porcelain_v2_emits_rename_record",
    "rename_sha256_repo_detected",
    "rename_sha256_worktree_exact_pairing",
    "rename_short_format_uses_arrow",
    "rename_untracked_config_cascade",
    "rename_untracked_true_uno_no_question_mark",
    "rename_untracked_true_uno_probe_success",
    "resolved_conflict_with_stage0_emits_no_u_line",
    "scan_complete_reports_all_untracked",
    "scan_snapshot_keeps_rename_endpoints_as_dirty_rows",
    "scan_survives_non_utf8_untracked_path",
    "seam_env_overrides_are_ignored_without_the_harness_gate",
    "seam_unreadable_mode_override_is_ignored_without_the_harness_gate",
    "short_forced_color_keeps_raw_high_bytes_with_quote_path_false",
    "short_non_utf8_quote_path_false_writes_raw_high_bytes",
    "short_quote_path_core_false",
    "short_rename_keeps_staged_source_component",
    "short_z_rename_record_is_raw_new_then_old",
    "similarity_budget_warning",
    "st_bare_z_emits_porcelain_v1",
    "staged_rename_then_delete_emits_rd",
    "staged_rename_then_modify_emits_rm",
    "status_short_value_contains_s_not_short",
    "symlink_rename_hashes_target_bytes_not_referent",
    "symlink_worktree_exact_with_rename_untracked",
    "tracked_non_utf8_path_never_fails_status",
    "tracked_scan_eacces_partial_json",
    "tracked_scan_io_timeout_is_reported_not_hung",
    "tracked_unreadable_path_fails_closed_not_deleted",
    "unmerged_path_never_pairs_as_a_staged_rename_source",
    "unmerged_stage_presence_to_xy_mapping",
    "untracked_dir_marker_keeps_raw_bytes_with_quote_path_false",
    "valid_short_clusters_select_short_and_nul",
    "worktree_candidate_not_found_between_scan_and_hash",
    "worktree_candidate_vanishes_between_scan_and_hash",
    "worktree_exact_matches_known_index_oid",
    "worktree_read_failure_degrades_with_warning_not_silence",
    "worktree_type_race_between_stat_and_hash_drops_candidate",
];

/// Names in [`STATUS_WAVE0_TESTS`] whose test functions are gated
/// `#[cfg(unix)]` in `tests/command/status_wave0_test.rs` — the canonical
/// platform inventory. The gate's source-level collection sees every
/// declaration regardless of `cfg`, so this list is not used to filter the
/// expected set; it is asserted unique and a subset of
/// [`STATUS_WAVE0_TESTS`], strictly alphabetically sorted.
pub const STATUS_WAVE0_TESTS_UNIX_ONLY: &[&str] = &[
    "cache_fallback_still_fails_closed_on_io_blocked",
    "check_dirty_blocked_rows_never_mutate_the_cache",
    "check_dirty_ioblocked_emits_warning_and_exit_nine",
    "check_dirty_modified_row_content_hash_failure_is_blocked_and_kept",
    "diff_and_status_agree_on_inexact_stages",
    "json_base_and_rename_completeness_matrix",
    "json_io_blocked_non_utf8_path_reversible",
    "json_io_blocked_rename_branch_schema",
    "json_scan_with_pathspec_reports_blocks_outside_it",
    "non_utf8_arguments_do_not_abort_the_process",
    "non_utf8_path_skips_rename_not_status",
    "object_read_unavailable_blob_skips_inexact_only",
    "object_read_unavailable_warning_is_deduplicated",
    "pathspec_filter_keeps_non_event_worktree_warnings",
    "porcelain_v2_non_rename_rows_from_subdirectory_keep_real_metadata",
    "porcelain_v2_unmerged_row_from_subdirectory_keeps_real_worktree_mode",
    "porcelain_z_non_utf8_base_status_raw_bytes",
    "probe_eacces_then_truncated_keeps_both",
    "probe_glob_pathspec_keeps_blocked_directory_relevant",
    "probe_marker_collapse_is_per_root",
    "probe_never_reads_a_non_regular_candidate",
    "probe_pathspec_outside_eacces_not_propagated",
    "probe_records_escape_for_a_metadata_root_behind_a_symlink",
    "probe_symlinked_escape_is_reported_not_followed",
    "quiet_does_not_bypass_io_blocked_fail_closed",
    "quiet_unreadable_untracked_dir_fails_closed",
    "scan_survives_non_utf8_untracked_path",
    "short_forced_color_keeps_raw_high_bytes_with_quote_path_false",
    "short_non_utf8_quote_path_false_writes_raw_high_bytes",
    "symlink_rename_hashes_target_bytes_not_referent",
    "symlink_worktree_exact_with_rename_untracked",
    "tracked_non_utf8_path_never_fails_status",
    "tracked_scan_io_timeout_is_reported_not_hung",
    "tracked_unreadable_path_fails_closed_not_deleted",
    "untracked_dir_marker_keeps_raw_bytes_with_quote_path_false",
    "worktree_candidate_not_found_between_scan_and_hash",
    "worktree_candidate_vanishes_between_scan_and_hash",
    "worktree_read_failure_degrades_with_warning_not_silence",
];
